[versions]
agp = "8.2.2"
appauth = "0.11.1"
coil-compose = "2.5.0"
dagger-compiler = "2.48"
datastore-preferences = "1.0.0"
google-api-client-android = "2.2.0"
google-api-services-youtube = "v3-rev20231011-2.0.0"
google-http-client-android = "1.43.3"
hilt-android-compiler = "2.44"
hilt-compiler = "2.48"
kotlin = "1.9.22"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.01.00"
credential-manager = "1.2.0"
googleid =   "1.1.0"
googleid-one-tap = "20.7.0"
ksp =  "1.9.0-1.0.12"
hilt = "2.48"
hilt-androidx = "1.1.0"
material-icons-extended = "1.6.0"
navigation-compose = "2.7.6"
runtime-tracing = "1.0.0-beta01"

[libraries]
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx"}
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-compose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-compose" }
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

animation = { module = "androidx.compose.animation:animation"}
foundation = { group = "androidx.compose.foundation", name = "foundation"}
runtime = { module = "androidx.compose.runtime:runtime"}
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material = { group = "androidx.compose.material", name = "material"}
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtime-tracing" }

google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "google-api-client-android" }
google-api-client-gson = { module = "com.google.api-client:google-api-client-gson", version.ref = "google-api-client-android" }
google-api-services-youtube = { module = "com.google.apis:google-api-services-youtube", version.ref = "google-api-services-youtube" }
google-http-client-android = { module = "com.google.http-client:google-http-client-android", version.ref = "google-http-client-android" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credential-manager"}
credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credential-manager"}
identity = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid"}
one-tap-sign-in = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleid-one-tap"}

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hilt-androidx"}
hilt-navigation = { module = "androidx.hilt:hilt-navigation", version.ref = "hilt-androidx"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-androidx"}
hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hilt-androidx"}

hilt-compilerx = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-androidx"}
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-compiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android-compiler" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-compiler" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[bundles]
credential-manager = ["credentials", "credentials-play-services-auth", "identity", "one-tap-sign-in"]
hilt = ["hilt-android", "hilt-common", "hilt-navigation", "hilt-navigation-compose", "hilt-navigation-fragment"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref  = "ksp" }
hilt = {id = "com.google.dagger.hilt.android", version.ref = "hilt"}

